order-book:
  wssURI: "wss://ws.kraken.com/"
  pairs: "XBT/USD"
  candle:
    output: "console"
    rounding-mode: "CEILING"

spring:
  main:
    web-application-type: none
    lazy-initialization: false