order-book:
  wssURI: "wss://ws.kraken.com/"
  pairs: "XBT/USD"
  depth: 10
  candle:
    output: "console"
    rounding-mode: "CEILING"
  kafka:
    topic-prefix: local
    consumers:
      group-id: analytics.group
      client-id-prefix: analytics
      candle:
        topic: "${order-book.kafka.topic-prefix}-candleEvents"
    producers:
      candle:
        topic: "${order-book.kafka.topic-prefix}-candleEvents"

spring:
  main:
    web-application-type: none
    lazy-initialization: false
  kafka:
    properties:
      request.timeout.ms: 20000
      retry.backoff.ms: 500
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.ByteArrayDeserializer
      isolation-level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: record

